const tipsList = [
  "Make a list the night before.",
  "Wake up earlier.",
  "Stay organized.",
  "Keep to a schedule.",
  "Break your day into time slots.",
  "Maintain a list of backburner tasks.",
  "Come up with a prioritization system.",
  "Define both urgency and importance.",
  "Consider the mental elements of tasks.",
  "Break big projects down into bite-sized tasks.",
  "Procrastinate some tasks.",
  "Rehearse conversations.",
  "Schedule conservatively.",
  "If it takes less than 2 minutes, do it now.",
  "Focus on objectives or outcomes, rather than tasks.",
  "Don’t plan too rigidly.",
  "Accomplish something early in the morning.",
  "Visualize yourself achieving your goals.",
  "Do your most difficult tasks first.",
  "Reduce the number of distractions in your environment.",
  "Take unnecessary devices out of the picture.",
  "Learn to say no.",
  "Delegate tasks beneath your paygrade.",
  "Set deadlines for yourself.",
  "Create the right level of ambient noise.",
  "Turn off notifications.",
  "Stop multitasking.",
  "Do creative or brainstorming work early.",
  "Reward yourself.",
  "Try striking a power pose.",
  "Talk to people you love.",
  "Find a reason to laugh.",
  "Change how you think about stress.",
  "Change how you think about failure.",
  "Meditate.",
  "Reduce decision fatigue.",
  "Be more decisive.",
  "Read and listen to quotes on productivity.",
  "Keep a list of accomplishments.",
  "Learn to master flow.",
  "End each day on a high note.",
  "Eliminate perfectionism.",
  "Invest in your own happiness.",
  "Tackle hard jobs by committing to just 5 minutes.",
  "Be part of a community.",
  "Focus on quality, not quantity.",
  "But don’t forget about quantity, either.",
  "Eat breakfast.",
  "Get the right nutrition throughout the day.",
  "Stay hydrated.",
  "Use caffeine wisely.",
  "Exercise.",
  "Get adequate sleep.",
  "Take a nap.",
  "Go outside.",
  "Invest in the right equipment.",
  "Limit and maximize your travel time.",
  "Change the temperature.",
  "Work in a new environment.",
  "Add a pleasant fragrance.",
  "Look at interesting art.",
  "Pet a dog (or cat).",
  "Keep your desk clean.",
  "Know your most productive periods.",
  "Limit when and how you check email.",
  "Establish a “communication” time.",
  "Limit your number of meetings.",
  "Limit your meeting time.",
  "Keep your meetings on schedule.",
  "Take lots of breaks.",
  "Break in the middle of tasks.",
  "Go on vacation at least once a year.",
  "Set a timer for allowed distractions.",
  "Make use of time you spend waiting.",
  "Regularly schedule catch up/maintenance days.",
  "Make good use of weekends.",
  "Have a firm cutoff time.",
  "Decompress after trying to solve a tough problem.",
  "Define productivity as less work, not more.",
  "Set up automatic email filters.",
  "Use canned responses.",
  "Experiment with Gmail addons and apps.",
  "Automate simple tasks.",
  "Dictate notes rather than writing.",
  "Create templates.",
  "Learn keyboard shortcuts.",
  "Shorten all your communications.",
  "Master all our Gmail hacks.",
  "Reduce the number of “time-saving” apps you use.",
  "Improve your abilities.",
  "Know when someone else could do this faster.",
  "Track your time.",
  "Measure your emails.",
  "Keep a journal.",
  "Work with a mentor.",
  "Take snapshots of your progress.",
  "Isolate your variables.",
  "Be aware of (and change) your habits.",
  "Talk to other people.",
  "Experiment.",
  "Take things one step at a time.",
];

export default tipsList;
